site_name: Script to commit changes, then submit and merge a pull request
site_url: https://josh-wong.github.io/commit-submit-merge-script/

# Add repo details in the top right-hand corner
repo_name: josh-wong/commit-submit-merge-script
repo_url: https://github.com/josh-wong/commit-submit-merge-script/
edit_uri: blob/main/docs

plugins:
  - search
  #- techdocs-core
  - git-revision-date-localized:
      type: date
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - git-committers:
      repository: josh-wong/commit-submit-merge-script
      branch: main

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # Add support for Material for MkDocs admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      # Add link next to header that allows the user to get a permalink to the heading (still need to copy the URL in the address bar).
      permalink: true

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/mkdocs_robot.png
  icon:
    repo: fontawesome/brands/github
    # Add icons for Material for MkDocs admonitions
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: grey
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: grey
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Configuring the script: '02_configuring-script.md'
  - Conclusion: '03_conclusion.md'
  - References: '04_references.md'
  - Contributions: '05_contributions.md'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'
  