site_name: Script to commit changes, then submit and merge a pull request
site_url: https://josh-wong.github.io/commit-submit-merge-script/

# Add repo details in the top right-hand corner
repo_name: josh-wong/commit-submit-merge-script
repo_url: https://github.com/josh-wong/commit-submit-merge-script/
edit_uri: blob/main/docs

plugins:
  - search
  - techdocs-core
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  favicon: assets/images/favicon.png
  # logo: assets/images/<ADD LOGO>.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: blue
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josh-wong
      name: josh-wong on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wongjoshua
      name: Joshua Wong on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/josh_in_japan
      name: josh_in_japan on Twitter

nav:
  - Overview: 'index.md'
  - Contributions: '05_contributions.md'
  - '': ''
  - '': ''
  - 🏠Home: 'https://josh-wong.github.io'